version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: develcode-db
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: develcode 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-net
    restart: always

networks:
  mysql-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local

